### ISSUE TITLE
1.【前端小白入门系列】css布局之两列布局

### ISSUE THREAD

**Issue by blff122620** [blff122620/blog#1]
今天说到css布局，我们来说一下css两列布局的一些实现方法,大概写了以下5种实现：
> 下面这5种方式各有优缺点，这里来大概说一下，第一种，代码简单直观，容易理解，但是IE6下有点bug，第二种是兼容性最好的，IE6也支持，但是结构略臃肿，第三种代码简单，触发了BFC，但是兼容性存在一定问题，第四种同样是兼容性问题+代码略多，不太建议采用，第五种，代码最简单，用了强大的flex，但是同样是兼容性问题，还有就是flex根据内容来进行渲染，容易出现性能问题，所以通常会用在小范围的布局处理，而不是整页的布局处理。
##  1. float + margin：
这种最经典的方式，页面结构如下：
```html
<div class="l left"></div>
<div class="content clearfix"></div>
```
样式如下：
```css
    .l {
        float: left;
    }
    
    .left {
        width: 200px;
        height: 300px;
        background: #ccc;
        border: 1px dotted green;
        /*margin-right：-200px; 解决IE6下面3像素的问题*/
    }
    
    .content { 
        margin-left: 220px;
        background: lightgreen;
        border: 1px dashed blue;
     }
```
这种在IE6下会有3像素的bug，需要hack一下
## 2.float + margin + fix
页面结构如下：
```html
<div class="l left">test</div>
<div class="right-fix">
    <div class="content ">

    </div>
</div>
```
```css
.l {
    float: left;
}

.left {
    width: 200px;
    height: 300px;
    background: #ccc;
    border: 1px dotted green;
    position: relative;/*z轴提前，被遮挡，所以要z轴提前*/
}
.right-fix{
    float: right; 
    width: 100%;
    margin-left: -220px;/*利用边距为负数将文档流往前移动，但是会遮挡住上面元素*/
}
.content {
    background: lightgreen;
    border: 1px dashed blue;
    margin-left: 220px;
}
```
## 3.float + overflow (触发了BFC)
结构和第一种实现一样
```html
<div class="l left"></div>
<div class="content clearfix"></div>
```
```css
.l {
    float: left;
}

.left {
    width: 200px;
    height: 300px;
    background: #ccc;
    border: 1px dotted green;
    margin-right: 20px;
    overflow: hidden;/*这里是为了让resize生效*/
    resize: horizontal;
}

.content {
    background: lightgreen;
    border: 1px dashed blue;
    overflow: hidden;/*触发BFC*/
}
```
## 4.table table-cell
```html
<div class="parent">
    <div class="l left">
    </div>
    <div class="content ">

    </div>
</div>
```
```css
.parent{
    display: table;
    width: 100%;
    table-layout: fixed;/*布局优先，加速渲染,与内容无关*/
}
.l{
    width: 200px;
    background: #ccc;
    border: 1px dotted green;
    padding-right: 20px;/*设置间距*/
    background-clip: content-box;
}
.content,.l{
    display: table-cell;
}
.content{
    background: lightgreen;
    border: 1px dashed blue;
}
```

## 5. flex
这个和第四种html结构一样，css如下：
```css
.parent{
    display:flex;
}
.l{
    width:200px;
    margin-right:20px;
}
.right{
    flex:1;
}
```
